function answ = defineAliases
% DEFINEALIASES Declaration of custom settings for parameters
%
%   defineAliases returns a 2xN cell array of parameter reassignments for 
%   use by processArgs.  They are meant to save certain modes of operation
%   for later use.
%
%   The alias definitions take the format as shown below. 
%
%   {'name', ...
%       {'variable1', answer1, ...};...

answ={'noroll',...
    {'preroll',0,'postroll',0};...
    'silent',...
    {'quiet',true,'plot',false,'pause',false,'playsample',false,'verbose',false};...
 'current',...
    {'plot',true,'pause',true,'playsample',false,'quiet',false,'Nsplits',100,...
    'powerThresh',10^-6.5,'doFilterNoise',false,...
    'syllable.minPower',3e-9, 'syllable.borderRise', 1e-7...
    'noiseLength',1.0,'noiseDynamicRange',2e-5,'noiseVariation',5e-6,...
    'dgram.minContrast',3e-11};...
 'Lb189',...
    {};...
 'Lb277',...
    {'powerThresh', 5e-6, 'syllable.minPower', 1e-5};...
 'Lb277-BOS',...
    {'powerThresh', 5e-6, 'syllable.minPower', 1e-5, 'syllable.comboLength', 10,...
    'syllable.borderRise', 5e-3};...
 'Db113',... % note, noise is high but signal is high as well
... % also, there is a bird singing in the background often, which is
... % at the same volume as the noise - we want to reject that too
    {'powerThresh', 2e-4, 'noiseVariation', 3e-4, 'noiseDynamicRange', 1e-3};...
  'Db113-BOS',... 
    {'powerThresh', 2e-4, 'syllable.minPower', 3.1e-7, 'dgram.minContrast',2e-10, 'syllable.borderRise',2e-5};...
 'Dg138',...
    {'powerThresh', 6e-5, 'syllable.minPower', 1e-6};...
 'Dg138-BOS',...
    {'powerThresh', 6e-5, 'syllable.minPower', 1e-6, 'syllable.borderRise', 2e-4,...
    'syllable.comboLength', 10, 'syllable.minLength', 10, 'dgram.minContrast', 2.2e-10};...
  'Gy242',...
  {'powerThresh', 3e-3, 'syllable.minPower', 1e-5, 'syllable.comboLength', 5, ...
  'minLength', 200};...
    'Y231',...     
    {'powerThresh', 1e-5, 'syllable.minPower', 3.1e-6,'noiseDynamicRange',9e-5, 'noiseVariation',1.8e-5};... 
 'Y231-BOS',...
     {'syllable.minPower',5e-7, 'syllable.borderRise', 8e-5};...
 'Y231early',...     
    {'powerThresh', 3e-5};
 'R204', ...
    {'powerThresh', 3e-6, 'syllable.minPower', 1e-7,...
    'noiseDynamicRange',6.5e-6, 'noiseVariation',1.3e-6}; ...
 'R204-BOS', ...
    {'powerThresh', 3e-6, 'syllable.minPower', 8e-8, 'syllable.borderRise',4e-6, ...
    'dgram.minContrast',5e-12}; ...
 'confidentPractice',...
    {'syllable.borderRise',1.2e-4,'syllable.minPower',1e-6,'dgram.minContrast',1e-9};...
 'shyPractice',...
    {'syllable.borderRise',1.2e-6,'syllable.minPower',3e-8,'dgram.minContrast',1e-11};...
 'splitty',...
    {'syllable.comboLength', 5}; % combine all adj. syllables with gaps 5ms or less
 'chunky',...
    {'syllable.comboLength', 30}; % combine all adj. syllables with gaps 30ms or less
    
 'R247', ...
  {'syllable.minPower', 5e-7}; ...
 'R247-BOS', ...
  {'syllable.minPower',5e-7, 'syllable.borderRise', 8e-5,...
   'syllable.comboLength',10}; ...
 'R288', ...
  {};...
 'R288-BOS',...
  {'syllable.minPower',5e-7, 'syllable.borderRise', 8e-5,...
        'syllable.comboLength',5};...
 'Gy217',...
 {'syllable.minPower',1.7e-6, 'syllable.borderRise', 1e-4, ...
 'syllable.minRiseAmp', 8, 'syllable.comboLength', 10, 'dgram.minContrast',3e-11} ...       
};
